- name: Remove the Docker Config object for MKE
  ansible.builtin.command: docker config rm com.docker.ucp.config
  delegate_to: "{{ main_manager }}"
  ignore_errors: true
  when: mke_config_src != ""
  run_once: true
